"use client";

import React from "react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import {
  KeyRound,
  FileCheck2,
  PlayCircle,
  Award,
  ArrowRight,
  ShieldCheck,
  CheckCircle2,
  Terminal,
  BrainCircuit,
  QrCode
} from "lucide-react";

export function StudentJourneyFlow() {
  const steps = [
    {
      num: "Step 1",
      icon: KeyRound,
      title: "Login with College Email & Password",
      desc: "Students use credentials generated by your college administrator. Dedicated auth ensures strict institutional isolation.",
      badge: "Secure Access"
    },
    {
      num: "Step 2",
      icon: FileCheck2,
      title: "Basic Details Verification",
      desc: "One-time entry of University Register Number, Department, Year, and Section to bind academic CIE records.",
      badge: "5-Field Quick Form"
    },
    {
      num: "Step 3",
      icon: PlayCircle,
      title: "4-Part Virtual Lab Simulation",
      desc: "Hands-on practice with step-by-step state animations, JVM stack tracers, and instant self-assessment quizzes.",
      badge: "Interactive Learning"
    },
    {
      num: "Step 4",
      icon: Award,
      title: "Personal Student Dashboard & Certificate",
      desc: "Tracks lab completion % and generates a verified, printable completion certificate with a tamper-proof QR badge.",
      badge: "Accredited Outcome"
    }
  ];

  return (
    <section className="py-20 md:py-28 bg-background border-b border-border/60 relative">
      <div className="container max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-3xl mx-auto mb-16 space-y-4">
          <Badge variant="outline" className="text-xs uppercase font-mono px-3 py-1 bg-rose-500/10 text-rose-500 border-rose-500/25">
            Learner Journey
          </Badge>
          <h2 className="text-3xl sm:text-4xl font-extrabold font-heading text-foreground tracking-tight">
            Seamless Student Onboarding &amp; Verification Flow
          </h2>
          <p className="text-sm sm:text-base text-muted-foreground leading-relaxed">
            From entering their institutional credentials to earning their verified laboratory certificate — designed for maximum engagement and zero confusion.
          </p>
        </div>

        {/* 4 Cards Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {steps.map((s, idx) => {
            const Icon = s.icon;
            return (
              <div
                key={s.num}
                className="p-6 rounded-2xl border border-border/80 bg-card/60 backdrop-blur-xs flex flex-col justify-between space-y-4 relative shadow-xs hover:border-rose-500/40 hover:shadow-lg transition-all"
              >
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-xs font-bold text-rose-600 uppercase tracking-wider">
                      {s.num}
                    </span>
                    <Badge variant="secondary" className="text-[10px] font-mono">
                      {s.badge}
                    </Badge>
                  </div>

                  <div className="w-12 h-12 rounded-xl bg-rose-500/10 text-rose-600 flex items-center justify-center">
                    <Icon className="h-6 w-6" />
                  </div>

                  <h3 className="font-bold text-base font-heading text-foreground leading-snug">
                    {s.title}
                  </h3>

                  <p className="text-xs text-muted-foreground leading-relaxed">
                    {s.desc}
                  </p>
                </div>

                <div className="pt-2">
                  <div className="w-full h-1 bg-muted rounded-full overflow-hidden">
                    <div
                      className="h-full bg-rose-600 rounded-full"
                      style={{ width: `${(idx + 1) * 25}%` }}
                    />
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
